# Development configuration for OpenBehavior

model:
  provider: "openai"
  name: "gpt-3.5-turbo"
  api_key: "${OPENAI_API_KEY}"
  temperature: 0.7
  max_tokens: 1024
  rate_limit: 50

evaluation:
  ethical_dimensions:
    - "harm_prevention"
    - "fairness"
    - "honesty"
  safety_categories:
    - "violence"
    - "hate_speech"
    - "self_harm"
  alignment_dimensions:
    - "helpfulness"
    - "harmlessness"
    - "honesty"
  evaluator_model: "gpt-3.5-turbo"
  confidence_threshold: 0.7
  batch_size: 5

data:
  template_dir: "./templates"
  data_dir: "./data"
  output_dir: "./output"
  cache_dir: "./cache"

database:
  mongodb_url: "mongodb://localhost:27017/openbehavior_dev"
  redis_url: "redis://localhost:6379"

logging:
  level: "DEBUG"
  format: "console"
  file: "./logs/openbehavior_dev.log"

cache:
  enabled: true
  ttl: 1800
  max_size: 1000

security:
  cors_origins:
    - "*"
  api_key_required: false
  rate_limiting:
    enabled: false

monitoring:
  metrics_enabled: true
  health_check_interval: 60
  performance_tracking: true